import os
from pathlib import Path
from typing import Optional

class Skill:
    """
    Base class for Entigram Agent Skills.
    In Entigram, a skill is a set of instructions and metadata that guides an agent.
    """
    def __init__(self, name: str, instructions: str = ""):
        self.name = name
        self.instructions = instructions

    def get_instructions(self) -> str:
        return self.instructions

class PackageBuilder(Skill):
    """
    The PackageBuilder is a specialized Skill that knows how to 
    generate and structure new Entigram packages.
    
    It 'inherits from a skill' both in terms of class hierarchy 
    and in its ability to consume skill definitions.
    """
    def __init__(self):
        super().__init__(
            name="PackageBuilder",
            instructions="Expert at bootstrapping Entigram packages with Schema, Ontology, and Skills."
        )

    def create_package(self, 
                       name: str, 
                       output_dir: str = ".etg/packages", 
                       base_skill: Optional[str] = None, 
                       depends_on: Optional[str] = None,
                       namespace: str = "@custom") -> str:
        """
        Creates a new Entigram package directory with the standard components.
        Supports namespaces (e.g., @custom/MyPackage).
        """
        if "/" in name:
            namespace, name = name.split("/")

        pkg_path = Path(output_dir) / namespace / name
        pkg_path.mkdir(parents=True, exist_ok=True)
        
        # 0. Generate manifest (.etg/entigram.yaml)
        self._generate_manifest(pkg_path, namespace, name, depends_on)

        # 1. Generate Entigram Schema (schema.lds)
        schema_content = self._generate_default_schema(name)
        (pkg_path / "schema.lds").write_text(schema_content)

        # 2. Generate Agent Skill (SKILL.md)
        skill_content = self._generate_skill_md(name, base_skill, depends_on)
        (pkg_path / "SKILL.md").write_text(skill_content)

        # 3. Generate Ontology (schema.ttl)
        ontology_content = self._generate_default_ontology(name)
        (pkg_path / "schema.ttl").write_text(ontology_content)

        # 4. Generate Package Test (test_package.py)
        test_content = self._generate_test_py(name)
        (pkg_path / "test_package.py").write_text(test_content)

        return str(pkg_path)

    def create_package_from_schema(self, 
                                schema_path: str,
                                name: Optional[str] = None,
                                output_dir: str = ".etg/packages",
                                base_skill: Optional[str] = None) -> str:
        """
        Bootstraps a package using an existing Schema file as the core.
        """
        schema_p = Path(schema_path)
        if not schema_p.exists():
            raise FileNotFoundError(f"Schema file not found: {schema_path}")
        
        pkg_name = name or schema_p.stem
        pkg_path = Path(output_dir) / pkg_name
        pkg_path.mkdir(parents=True, exist_ok=True)

        # 1. Copy/Write Schema
        (pkg_path / "schema.lds").write_text(schema_p.read_text())

        # 2. Generate Agent Skill
        skill_content = self._generate_skill_md(pkg_name, base_skill, output_dir=output_dir)
        (pkg_path / "SKILL.md").write_text(skill_content)

        # 3. Generate Ontology placeholder
        ontology_content = self._generate_default_ontology(pkg_name)
        (pkg_path / "schema.ttl").write_text(ontology_content)

        # 4. Generate Package Test
        test_content = self._generate_test_py(pkg_name)
        (pkg_path / "test_package.py").write_text(test_content)

        return str(pkg_path)

    def _generate_manifest(self, pkg_path: Path, namespace: str, name: str, depends_on: Optional[str] = None):
        import yaml
        entigram_dir = pkg_path / ".etg"
        entigram_dir.mkdir(parents=True, exist_ok=True)
        
        manifest = {
            "namespace": namespace,
            "name": name,
            "version": "0.0.1",
            "tier": "community",
            "license": "MIT",
            "requires_hosted_ledger": False,
            "dependencies": {}
        }
        
        if depends_on:
            manifest["dependencies"][depends_on] = "latest"
            
        with open(entigram_dir / "entigram.yaml", "w") as f:
            yaml.dump(manifest, f, default_flow_style=False, sort_keys=False)

    def _generate_default_schema(self, name: str) -> str:
        return f"""/* 
 * {name} Entigram Schema 
 * Generated by Entigram PackageBuilder
 */

ENTITY {name} {{
    id UUID PK
    name String
    created_at DateTime
}}
"""

    def _generate_test_py(self, name: str) -> str:
        return f"""import unittest
import os
from pathlib import Path
from entigram.schema_compiler.parser import SchemaParser

class Test{name}Package(unittest.TestCase):
    def setUp(self):
        self.pkg_dir = Path(__file__).parent
        self.schema_path = self.pkg_dir / "schema.lds"
        self.skill_path = self.pkg_dir / "SKILL.md"
        self.ontology_path = self.pkg_dir / "schema.ttl"

    def test_schema_exists(self):
        self.assertTrue(self.schema_path.exists())

    def test_skill_exists(self):
        self.assertTrue(self.skill_path.exists())

    def test_ontology_exists(self):
        self.assertTrue(self.ontology_path.exists())

    def test_schema_parsable(self):
        content = self.schema_path.read_text()
        parser = SchemaParser(content)
        entities, relationships = parser.parse()
        self.assertGreater(len(entities), 0)

if __name__ == "__main__":
    unittest.main()
"""

    def create_package_from_description(self, 
                                       name: str, 
                                       description: str,
                                       output_dir: str = ".etg/packages") -> str:
        """
        Uses a heuristic (or later, an LLM) to generate a detailed Schema from a description.
        For now, it scaffolds a more advanced template based on common patterns.
        """
        pkg_path = Path(output_dir) / name
        pkg_path.mkdir(parents=True, exist_ok=True)

        # 1. Generate Advanced Schema from Description
        schema_content = self._scaffold_schema_from_description(name, description)
        (pkg_path / "schema.lds").write_text(schema_content)

        # 2. Generate Agent Skill
        skill_content = self._generate_skill_md(name)
        (pkg_path / "SKILL.md").write_text(skill_content)

        # 3. Generate Ontology
        ontology_content = self._generate_default_ontology(name)
        (pkg_path / "schema.ttl").write_text(ontology_content)

        # 4. Generate Package Test
        test_content = self._generate_test_py(name)
        (pkg_path / "test_package.py").write_text(test_content)

        return str(pkg_path)

    def _scaffold_schema_from_description(self, name: str, description: str) -> str:
        """
        Heuristic-based Schema scaffolding. 
        In a real scenario, this would involve a prompt to an LLM.
        """
        return f"""/* 
 * {name} Entigram Schema 
 * Description: {description}
 * Generated by Entigram PackageBuilder (Discovery Mode)
 */

ENTITY: {name}_Core
ATTRIBUTES:
  - id (UUID, PK)
  - name (String)
  - description (String)
  - status (String) # Active, Inactive, Draft
  - created_at (DateTime)

ENTITY: {name}_Event
ATTRIBUTES:
  - id (UUID, PK)
  - event_type (String)
  - payload (JSON)
  - occurred_at (DateTime)

RELATIONSHIP: {name}_Core (1) [MUST] --- [MAY] (MANY) {name}_Event
"""

    def _generate_default_ontology(self, name: str) -> str:
        return f"""@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix mk: <http://entigram.ai/ontology/{name.lower()}#> .

mk:Ontology a owl:Ontology ;
    rdfs:label "{name} Ontology" ;
    rdfs:comment "Auto-generated ontology for the {name} package." .

mk:{name} a owl:Class ;
    rdfs:label "{name}" .

mk:{name}_name a owl:DatatypeProperty ;
    rdfs:domain mk:{name} ;
    rdfs:range xsd:string ;
    rdfs:label "name" .
"""

    def _generate_skill_md(self, name: str, base_skill: Optional[str] = None, depends_on: Optional[str] = None, output_dir: str = ".etg/packages") -> str:
        md = f"# {name} Skill\n\n"
        md += f"This skill manages the **{name}** domain within the Entigram Federated Architecture.\n\n"
        
        if base_skill:
            md += f"## Inheritance\n- **Base Skill:** `{base_skill}`\n\n"
        
        if depends_on:
            md += f"## Dependencies\n- **Depends on:** `{depends_on}`\n\n"

        md += "## Directives\n"
        md += "1. Use `schema.lds` for all data modeling decisions.\n"
        md += "2. Align external integrations with the classes defined in `schema.ttl`.\n"
        md += "3. Ensure domain isolation; do not leak state outside of this package's boundaries.\n\n"
        
        # New: Domain-Specific Directives from Schema
        pkg_path = Path(output_dir) / name
        schema_file = pkg_path / "schema.lds"
        if schema_file.exists():
            from entigram.schema_compiler.parser import SchemaParser
            try:
                parser = SchemaParser(schema_file.read_text())
                entities, _ = parser.parse()
                if entities:
                    md += "## Domain Entities\n"
                    md += "You are responsible for the lifecycle of the following entities:\n"
                    for ent_name in entities.keys():
                        md += f"- **{ent_name}**: Ensure all state transitions for {ent_name} are valid.\n"
                    md += "\n"
            except:
                pass

        md += "## Reusable Modules\n"
        md += "- **Schema:** `schema.lds` (Logical model)\n"
        md += "- **Ontology:** `schema.ttl` (Semantic model)\n"
        
        return md
